misperris/blog/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages

app_name='blog' 

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^base', views.base, name='base'),
    url(r'^Registro', views.registro, name='registro'),
    path('ajax/load-cities/', views.load_ciudades, name='load_ciudades'),
    url(r'^mascota/new/$', views.mascota_new, name='mascota_new'),
    url(r'^Mascota_List',views.mascota_list,name='mascota_list'),
    url(r'^mascota/(?P<pk>[0-9]+)/$', views.mascota_detail, name='mascota_detail'),
    url(r'^mascota/(?P<pk>[0-9]+)/edit/$', views.mascota_edit, name='mascota_edit'),
    url(r'^mascota/(?P<pk>[0-9]+)/delete/$', views.mascota_delete, name='mascota_delete'),

]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misperris/misperris/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from rest_framework import routers
from django.urls import path
from blog.quickstart import views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'Mascotas', views.MascotaViewSet)



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('blog.urls')),
    url(r'^password/', include('password_reset.urls')),
    url(r'^', include(router.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- 
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root':settings.MEDIA_ROOT,
        }),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misperris/password_reset/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^recover/(?P<signature>.+)/$', views.recover_done,
        name='password_reset_sent'),
    url(r'^recover/$', views.recover, name='password_reset_recover'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_done'),
    url(r'^reset/(?P<token>[\w:-]+)/$', views.reset,
        name='password_reset_reset'),
]

misperris/password_reset/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.validators import validate_email
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class PasswordRecoveryForm(forms.Form):
    username_or_email = forms.CharField()

    error_messages = {
        'not_found': _("Sorry, this user doesn't exist."),
    }

    def __init__(self, *args, **kwargs):
        self.case_sensitive = kwargs.pop('case_sensitive', True)
        search_fields = kwargs.pop('search_fields', ('username', 'email'))
        super(PasswordRecoveryForm, self).__init__(*args, **kwargs)

        message = ("No other fields than username and email are supported "
                   "by default")
        if len(search_fields) not in (1, 2):
            raise ValueError(message)
        for field in search_fields:
            if field not in ['username', 'email']:
                raise ValueError(message)

        labels = {
            'username': _('Username'),
            'email': _('Email'),
            'both': _('Username or Email'),
        }
        User = get_user_model()  # noqa
        if getattr(User, 'USERNAME_FIELD', 'username') == 'email':
            self.label_key = 'email'
        elif len(search_fields) == 1:
            self.label_key = search_fields[0]
        else:
            self.label_key = 'both'
        self.fields['username_or_email'].label = labels[self.label_key]

    def clean_username_or_email(self):
        username = self.cleaned_data['username_or_email']
        cleaner = getattr(self, 'get_user_by_%s' % self.label_key)
        self.cleaned_data['user'] = user = cleaner(username)

        user_is_active = getattr(user, 'is_active', True)
        recovery_only_active_users = getattr(settings,
                                             'RECOVER_ONLY_ACTIVE_USERS',
                                             False)

        if recovery_only_active_users and not user_is_active:
            raise forms.ValidationError(_("Sorry, inactive users can't "
                                        "recover their password."))

        return username

    def get_user_by_username(self, username):
        key = 'username__%sexact' % ('' if self.case_sensitive else 'i')
        User = get_user_model()
        try:
            user = User._default_manager.get(**{key: username})
        except User.DoesNotExist:
            raise forms.ValidationError(self.error_messages['not_found'],
                                        code='not_found')
        return user

    def get_user_by_email(self, email):
        validate_email(email)
        key = 'email__%sexact' % ('' if self.case_sensitive else 'i')
        User = get_user_model()
        try:
            user = User._default_manager.get(**{key: email})
        except User.DoesNotExist:
            raise forms.ValidationError(self.error_messages['not_found'],
                                        code='not_found')
        return user

    def get_user_by_both(self, username):
        key = '__%sexact'
        key = key % '' if self.case_sensitive else key % 'i'

        def f(field):
            return Q(**{field + key: username})
        filters = f('username') | f('email')
        User = get_user_model()
        try:
            user = User._default_manager.get(filters)
        except User.DoesNotExist:
            raise forms.ValidationError(self.error_messages['not_found'],
                                        code='not_found')
        except User.MultipleObjectsReturned:
            raise forms.ValidationError(_("Unable to find user."))

        return user


class PasswordResetForm(forms.Form):
    password1 = forms.CharField(
        label=_('New password'),
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label=_('New password (confirm)'),
        widget=forms.PasswordInput,
    )

    error_messages = {
        'password_mismatch': _("The two passwords didn't match."),
    }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PasswordResetForm, self).__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1', '')
        password2 = self.cleaned_data['password2']
        if not password1 == password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch')
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['password1'])
        if commit:
            get_user_model()._default_manager.filter(pk=self.user.pk).update(
                password=self.user.password,
            )
        return self.user

misperris/password_reset/views.py
import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core import signing
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.debug import sensitive_post_parameters


from .forms import PasswordRecoveryForm, PasswordResetForm
from .signals import user_recovers_password


class SaltMixin(object):
    salt = 'password_recovery'
    url_salt = 'password_recovery_url'


def loads_with_timestamp(value, salt):
    """Returns the unsigned value along with its timestamp, the time when it
    got dumped."""
    try:
        signing.loads(value, salt=salt, max_age=-999999)
    except signing.SignatureExpired as e:
        age = float(str(e).split('Signature age ')[1].split(' >')[0])
        timestamp = timezone.now() - datetime.timedelta(seconds=age)
        return timestamp, signing.loads(value, salt=salt)


class RecoverDone(SaltMixin, generic.TemplateView):
    template_name = 'password_reset/reset_sent.html'

    def get_context_data(self, **kwargs):
        ctx = super(RecoverDone, self).get_context_data(**kwargs)
        try:
            ctx['timestamp'], ctx['email'] = loads_with_timestamp(
                self.kwargs['signature'], salt=self.url_salt,
            )
        except signing.BadSignature:
            raise Http404
        return ctx


recover_done = RecoverDone.as_view()


class Recover(SaltMixin, generic.FormView):
    case_sensitive = True
    form_class = PasswordRecoveryForm
    template_name = 'password_reset/recovery_form.html'
    success_url_name = 'password_reset_sent'
    email_template_name = 'password_reset/recovery_email.txt'
    email_subject_template_name = 'password_reset/recovery_email_subject.txt'
    search_fields = ['username', 'email']

    def get_success_url(self):
        return reverse(self.success_url_name, args=[self.mail_signature])

    def get_context_data(self, **kwargs):
        kwargs['url'] = self.request.get_full_path()
        return super(Recover, self).get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super(Recover, self).get_form_kwargs()
        kwargs.update({
            'case_sensitive': self.case_sensitive,
            'search_fields': self.search_fields,
        })
        return kwargs

    def get_site(self):
        return get_current_site(self.request)

    def send_notification(self):
        context = {
            'site': self.get_site(),
            'user': self.user,
            'username': self.user.get_username(),
            'token': signing.dumps(self.user.pk, salt=self.salt),
            'secure': self.request.is_secure(),
        }
        body = loader.render_to_string(self.email_template_name,
                                       context).strip()
        subject = loader.render_to_string(self.email_subject_template_name,
                                          context).strip()
        send_mail(subject, body, settings.DEFAULT_FROM_EMAIL,
                  [self.user.email])

    def form_valid(self, form):
        self.user = form.cleaned_data['user']
        self.send_notification()
        if (
            len(self.search_fields) == 1 and
            self.search_fields[0] == 'username'
        ):
            # if we only search by username, don't disclose the user email
            # since it may now be public information.
            email = self.user.username
        else:
            email = self.user.email
        self.mail_signature = signing.dumps(email, salt=self.url_salt)
        return super(Recover, self).form_valid(form)


recover = Recover.as_view()


class Reset(SaltMixin, generic.FormView):
    form_class = PasswordResetForm
    token_expires = None
    template_name = 'password_reset/reset.html'
    success_url = reverse_lazy('password_reset_done')

    def get_token_expires(self):
        duration = getattr(settings, 'PASSWORD_RESET_TOKEN_EXPIRES',
                           self.token_expires)
        if duration is None:
            duration = 3600 * 48  # Two days
        return duration

    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        self.user = None

        try:
            pk = signing.loads(kwargs['token'],
                               max_age=self.get_token_expires(),
                               salt=self.salt)
        except signing.BadSignature:
            return self.invalid()

        self.user = get_object_or_404(get_user_model(), pk=pk)
        return super(Reset, self).dispatch(request, *args, **kwargs)

    def invalid(self):
        return self.render_to_response(self.get_context_data(invalid=True))

    def get_form_kwargs(self):
        kwargs = super(Reset, self).get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super(Reset, self).get_context_data(**kwargs)
        if 'invalid' not in ctx:
            ctx.update({
                'username': self.user.get_username(),
                'token': self.kwargs['token'],
            })
        return ctx

    def form_valid(self, form):
        form.save()
        user_recovers_password.send(
            sender=get_user_model(),
            user=form.user,
            request=self.request
        )
        return redirect(self.get_success_url())


reset = Reset.as_view()


class ResetDone(generic.TemplateView):
    template_name = 'password_reset/recovery_done.html'


reset_done = ResetDone.as_view()

misperris/password_reset/templates/password_reset/base_pass.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">

<head>
    <title>Recuperación Contraseña - Mis Perris</title>
    <link rel="stylesheet" href="/static/style.css">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <header>
                    <nav>
                        <ul>
                            <li>
                                </a><img src="/static/IMG/logo.png" alt="logo">
                            </li>
                            <li>
                                <a href="{% url 'blog:home' %}">Inicio</a>
                            </li>
                            <li>
                                <a href="#">Quiénes Somos</a>
                            </li>
                            <li>
                                <a href="#">Servicios</a>
                            </li>
                            <li>
                                <a href="#">Contáctanos</a>
                            </li>
                        </ul>
                    </nav>
                </header>
                <br>
                <div class="row">
                    <div class="col-xs-12">
                            {% block content %}
                            {% endblock %}
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</body>

</html>

misperris/password_reset/templates/password_reset/recovery_done.html
{% extends 'password_reset/base_pass.html' %}
{% load i18n %}

{% block title %}{% trans "New password set" %}{% endblock %}

{% block content %}
<div class="confirm-changes">
	<p>{% trans "Tu contraseña ha sido modificada con éxito." %}</p>
	<br>
	<input type="button" name="accept" value="Aceptar" onClick="location.href='/accounts/login'">
</div>
	
{% endblock %}

misperris/password_reset/templates/password_reset/recovery_form.html
{% extends 'password_reset/base_pass.html' %}
{% load i18n %}

{% block title %}{% trans "Password recovery" %}{% endblock %}
{% block content %}

<div class="pass-form">
	<h1>Recupera tu contraseña</h1>
	<br>
	<form id="pass-form" method="post" action="{{ url }}">
		{% csrf_token %}
		{{ form.as_p }}
		<br>
		<p><input type="submit" name="pass-recover" value="{% trans 'Recuperar mi contraseña' %}"></p>
	</form>
</div>

{% endblock %}

misperris/password_reset/templates/password_reset/reset.html
{% extends 'password_reset/base_pass.html' %}
{% load i18n %}

{% block content %}
<div class="new-pass">
	<br>
	<h1>Recuperación de contraseña:</h1>
	<br>
	{% if invalid %}{% url "password_reset_recover" as recovery_url %}
	<p>{% blocktrans %}Lo sentimos, el link de recuperación de contraseña es inválido. Aún puedes <a href="{{ recovery_url }}">solicitar
			uno nuevo</a>.{% endblocktrans %}</p>
	{% else %}
	<p>{% blocktrans %}Hola, <strong>{{ username }}</strong>. Por favor escoge tu nueva contraseña:{% endblocktrans %}</p>
	<br>
	<form method="post" action="{% url 'password_reset_reset' token %}">
		{% csrf_token %}
		{{ form.as_p }}
		<br>
		<p><input type="submit" name="submit" value="{% trans 'Enviar' %}"></p>
	</form>
</div>

{% endif %}
{% endblock %}

misperris/password_reset/templates/password_reset/reset_sent.html
{% extends 'password_reset/base_pass.html' %}
{% load i18n %}

{% block title %}{% trans "Password recovery sent" %}{% endblock %}

{% block content %}
<div class="alert-pass">
	<p>{% blocktrans with ago=timestamp|timesince %}Un email ha sido enviado a <strong>{{ email }}</strong>. Use el link para establecer una nueva contraseña.{% endblocktrans %}</p>
	<br>
	<input type="button" name="back" value="Volver" onclick="history.go(-2)">
</div>
{% endblock %}