misperris/accounts/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import include, url
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)




app_name='accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^logout/$',views.logout_view, name="logout"),
]

misperris/blog/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages

app_name='blog' 

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^base', views.base, name='base'),
    url(r'^Registro', views.registro, name='registro'),
    path('ajax/load-cities/', views.load_ciudades, name='load_ciudades'),
    url(r'^mascota/new/$', views.mascota_new, name='mascota_new'),
    url(r'^Mascota_List',views.mascota_list,name='mascota_list'),
    url(r'^mascota/(?P<pk>[0-9]+)/$', views.mascota_detail, name='mascota_detail'),
    url(r'^mascota/(?P<pk>[0-9]+)/edit/$', views.mascota_edit, name='mascota_edit'),
    url(r'^mascota/(?P<pk>[0-9]+)/delete/$', views.mascota_delete, name='mascota_delete'),

]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misperris/misperris/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from rest_framework import routers
from django.urls import path
from blog.quickstart import views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'Mascotas', views.MascotaViewSet)



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('blog.urls')),
    url(r'^password/', include('password_reset.urls')),
    url(r'^', include(router.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- 
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root':settings.MEDIA_ROOT,
        }),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misperris/blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings


class Region(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Ciudad(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Usuario(models.Model):
    rut = models.CharField(max_length=12)
    nombre_completo = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    telefono = models.CharField(max_length=12,null=True)
    email = models.EmailField()
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.SET_NULL, null=True)
    tipo_vivienda_choices = (
                     ('PATIO_GRANDE','Casa con patio grande'),
                     ('PATIO_PEQUEÑO','Casa con patio pequeño'),
                     ('SIN_PATIO','Casa sin patio'),
                     ('DEPTO','Departamento'),
    )
    tipo_vivienda = models.CharField(max_length=30,choices=tipo_vivienda_choices,default='RESCATADO')
    author = models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    fecha_creacion = models.DateTimeField(
            default=timezone.now)
    fecha_publicacion = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.fecha_publicacion = timezone.now()
        self.save()

    def __str__(self):
        return self.rut

    class Meta:
        permissions = (
            ('usuario', _('Usuario')),
        )  


class Mascotas(models.Model):
    foto = models.ImageField(blank=True,null=True,upload_to="perro/%Y")
    nombre = models.CharField(max_length=30)
    raza = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=100)
    estado_choices = (
                     ('RESCATADO','Rescatado'),
                     ('DISPONIBLE','Disponible'),
                     ('ADOPTADO','Adoptado'),
    )
    estado = models.CharField(max_length=15,choices=estado_choices,default='RESCATADO')

    fecha_publicacion = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.fecha_publicacion = timezone.now()
        self.save()

    def __str__(self):
        return self.nombre

    class Meta:
        permissions = (
            ('mantenedor_mascotas', _('Mascotas')),
        )  



# Create your models here.

misperris/blog/forms.py
from django import forms
from .models import Usuario, Mascotas, Ciudad
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UsuarioForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ('rut', 'nombre_completo', 'fecha_nacimiento', 'telefono', 'email', 'region', 'ciudad', 'tipo_vivienda')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ciudad'].queryset = Ciudad.objects.none()

        if 'region' in self.data:
                try:
                    region_id = int(self.data.get('region'))
                    self.fields['ciudad'].queryset = Ciudad.objects.filter(region_id=region_id).order_by('nombre')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty Ciudad queryset
        elif self.instance.pk:
            self.fields['ciudad'].queryset = self.instance.region.ciudad_set.order_by('nombre')
            
class MascotasForm(forms.ModelForm):

    class Meta:
        model = Mascotas
        fields = ('foto','nombre','raza','descripcion','estado')

misperris/blog/quickstart/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from blog.quickstart.serializers import UserSerializer, MascotaSerializer
from blog.models import Mascotas

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

class MascotaViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Mascotas.objects.all()
    serializer_class = MascotaSerializer

misperris/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Usuario, Mascotas , Ciudad
from .forms import UsuarioForm
from .forms import MascotasForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required, permission_required
from . import forms
from django.http import HttpResponse



# Create your views here.
def home(request):
    mascotas = Mascotas.objects.all().order_by()
    return render(request, 'blog/Main.html', {'mascotas':mascotas })

    
    
def base(request):
    form = UsuarioForm()
    return render(request,'blog/base.html')


@login_required(login_url="/accounts/login/")
def registro(request):
    form = UsuarioForm()
    return render(request, 'blog/Registro.html', {'form': form})

@login_required(login_url="/accounts/login/")
def registro(request):
    if request.method == "POST":
        form = UsuarioForm(request.POST)
        if form.is_valid():
            usuario = form.save(commit=False)
            usuario.fecha_publicacion = timezone.now()
            usuario.author = request.user
            usuario.save()
            return redirect('blog:home')
    else:
        form = UsuarioForm()
    return render(request, 'blog/Registro.html', {'form': form})

def load_ciudades(request):
    region_id = request.GET.get('region')
    ciudades = Ciudad.objects.filter(region_id=region_id).order_by('nombre')
    return render(request, 'blog/ciudad_dropdown_list_options.html', {'ciudades': ciudades})

@login_required(login_url="/accounts/login/")
def mascota_list(request):
    user = request.user
    mascotas = Mascotas.objects.filter().order_by('fecha_publicacion')
    if user.has_perm('blog.admin'):
        return render(request, 'blog/Mascota_list.html', {'mascotas':mascotas})
    else:
        return render(request,'blog/Main.html')

@login_required(login_url="/accounts/login/")
def mascota_detail(request, pk):
    mascotas = get_object_or_404(Mascotas, pk=pk)
    return render(request, 'blog/mascota_detail.html', {'mascotas': mascotas})

@login_required(login_url="/accounts/login/")
def mascota_new(request):
    form = MascotasForm()
    return render(request, 'blog/mascota_edit.html', {'form': form})

@login_required(login_url="/accounts/login/")
def mascota_new(request):
    if request.method == "POST":
        form = MascotasForm(request.POST,request.FILES)
        if form.is_valid():
            mascota = form.save(commit=False)
            mascota.nombre = mascota.nombre
            mascota.fecha_publicacion = timezone.now()
            
            mascota.save()
            return redirect('blog:mascota_detail', pk=mascota.pk)
    else:
        form = MascotasForm()
    return render(request, 'blog/mascota_edit.html', {'form': form})

@login_required(login_url="/accounts/login/")
def mascota_edit(request, pk):
    mascota = get_object_or_404(Mascotas, pk=pk)
    if request.method == "POST":
        form = MascotasForm(request.POST,request.FILES, instance=mascota)
        if form.is_valid():
            mascota = form.save(commit=False)

            mascota.save()
            return redirect('blog:mascota_detail', pk=mascota.pk)
    else:
        form = MascotasForm(instance=mascota)
    return render(request, 'blog/mascota_edit.html', {'form': form})

@login_required(login_url="/accounts/login/")
def mascota_delete(request, pk):
    instance = get_object_or_404(Mascotas,pk=pk)
    instance.delete()
    return redirect('blog:mascota_list')

misperris/blog/templates/blog/Main.html
<!DOCTYPE html >
<html lang="es">
{% load static %}

<head>
    {% load pwa %} {% progressive_web_app_meta %}
    <meta name="msapplication-TileImage" content="static/icons/pet.png">
    <meta name="msapplication-TileColor" content="#2F3BA2">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Mis Perris</title>
    <script src="/static/Js/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="/static/fontsicon/style.css">
    <link rel="stylesheet" href="/static/css/flexboxgrid.css">
    <link rel="stylesheet" href="" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="static/Js/jquery.flexslider.js"></script>
    <link rel="stylesheet" href="/static/css/LightBox.css">
    <link rel="stylesheet" href="/static/css/flexslider.css">
    <script type="text/javascript" charset="utf-8">
        $(window).load(function () {
            $('.flexslider').flexslider();
        });
    </script>

    <script src="static/Js/script.js"></script>
    <link rel="stylesheet" href="/static/css/Style.css">
    
</head>

<body>
    <section class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <header>
                    <nav>
                        <ul>
                            <li>
                                <img src="/static/IMG/logo.png" alt="logo">
                            </li>
                            <li>
                                <a href="#">Inicio</a>
                            </li>
                            <li>
                                <a href="#">Quiénes Somos</a>
                            </li>
                            <li>
                                <a href="#">Servicios</a>
                            </li>
                            <li>
                                <a href="#">Contáctanos</a>
                            </li>

                            {% if user.is_authenticated %} {% if user.is_superuser %}

                            <li>
                                <a href="{% url 'blog:mascota_list' %}">Mascotas</a>
                            </li>
                            {% else %}
                            <li>
                                <a href="Registro.html">Postula AQUÍ!</a>
                            </li>
                            {% endif %}


                            <li style="font-size:22px" class="aviso-user">
                                <div class="connect-message">
                                    Conectado como: {{ request.user }}
                                </div>
                            </li>
                            <li>
                                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="salir" type="submit">Salir</button>
                                </form>
                            </li>

                            {% else %}
                            <li style="font-size:20px">
                                <a href="{% url 'accounts:login' %}">INGRESA</a>
                            </li>
                            {% endif %}

                        </ul>
                    </nav>

                </header>
            </div>
        </div>

        <section id="perro">
            <div class="row">
                <div class="col-xs-12">
                    <div class="flexslider">
                        {% for pets in mascotas %} {% if pets.estado == "ADOPTADO" %}
                        <ul class="slides">
                            <li>
                                <img src="{{ pets.foto.url }}" alt="apolo">

                                <section class="flex-caption">
                                    <p>{{pets.descripcion}}</p>
                                </section>
                            </li>
                            {% endif %} {% endfor %}
                    </div>
                </div>
            </div>
            <br>

            <div class="row">
                <div class="col-xs-12">
                    <footer>
                        <ul id="contacto">
                            <li>+569 98765431</li>
                            <li>Rescate y adopción de perros callejeros</li>
                            <li>
                                <ul id="redes">
                                    <li>
                                        <a href="https://www.facebook.com/">
                                            <span class="icon-facebook negro circulo"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://plus.google.com/">
                                            <span class="icon-google-plus negro circulo"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.instagram.com/">
                                            <span class="icon-instagram negro circulo"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://mail.google.com/">
                                            <span class="icon-mail2 negro circulo"></span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        <br>
                    </footer>
                </div>
            </div>
        </section>

        <div class="row">
            <section id="informacion">
                <article id="rescate">
                    <div class="col-xs-12">
                        <ul>
                            <li>
                                <br>
                                <h2>RESCATE</h2>
                            </li>
                            <li>
                                <h3>ETAPA UNO</h3>
                            </li>
                            <hr class="linea">
                            <li>
                                <p> Rescatamos perros en situación de peligro y/o abandono. Los rehabilitamos
                                    <br> y los preparamos para buscarles un hogar.</p>
                                <br>
                            </li>
                            <li>
                                <img src="/static/IMG/rescate.jpg" alt="rescate">
                            </li>
                        </ul>

                    </div>
                </article>
            </section>


            <aside id="asidemain">

                <div class="col-xs-12">
                    <ul>
                        <li>
                            <br>
                            <img src="/static/IMG/crowfunding.jpg" alt="crowdfunding">
                        </li>
                        <li>
                            <br>
                            <h2>CROWDFUNDING</h2>
                        </li>
                        <li>
                            <h3>FINANCIAMIENTO</h3>
                        </li>
                        <hr class="linea">
                        <li>
                            <p>
                                Sigue nuestras redes sociales para informarte acerca de las diversas campañas y
                                <br> actividades que realizamos para obtener financiamiento para seguir ayudando.
                            </p>
                        </li>
                        <li>
                            <br>
                            <br>
                            <a href="#" id="Campañas">
                                <b>CAMPAÑAS</b>
                            </a>
                        </li>
                    </ul>
                </div>
            </aside>
        </div>

    </section>

    <br>
    <br>
    <br>

    <section class="row center-xs">
        <ul class="galeria" id="fotografias">
            <div class="col-xs-6">
                <br>
                <h2>Disponibles</h2>
                <hr>
                <br> {% for pets in mascotas %} {% if pets.estado == "DISPONIBLE" %}
                <li class="galeria__item">
                    <h3>{{pets.nombre}}</h3>
                    <br>
                    <img src="{{pets.foto.url}}" class="galeria__img">
                    <section class="descripcion_perro">{{ pets.descripcion }}</section>
                </li>
                {% endif %} {% endfor %}
            </div>
            <div class="col-xs-6">
                <br>
                <h2>Rescatados</h2>
                <hr>
                <br> {% for pets in mascotas %} {% if pets.estado == "RESCATADO" %}
                <li class="galeria__item">
                    <h3>{{pets.nombre}}</h3>
                    <br>
                    <img src="{{pets.foto.url}}" class="galeria__img" width="284">
                    <section class="descripcion_perro">{{ pets.descripcion }}</section>
                </li>
                {% endif %} {% endfor %}
            </div>

        </ul>





        <script src="/static/Js/modal.js"></script>
    </section>
    <div class="row">
        <div class="col-xs-12">
            <footer id="piedepagina">
                <p>Desarrollo Web y Mobile</p>
                <br>
            </footer>
        </div>
    </div>



</body>

</html>

misperris/blog/templates/blog/Mascota_list.html
{% extends 'blog/base_mascotas.html' %}
{% block content %}


<div class=container-fluid>
    <div class="row">
        <div class="col-xs-12">
                <div class="mascota">
                        <h1>Mascotas "Mis Perris"</h1>
                        {% for mascota in mascotas %}
                        <br>
                        <div class="imagen_mascota">
                            <img class="centrado" style="height:400px" src="{{ mascota.foto.url }}" alt="mascota_img">
                        </div>
                        <div class="nombre_mascota">
                            <h2><a href="{% url 'blog:mascota_detail' pk=mascota.pk %}">{{ mascota.nombre }}</a></h2>
                        </div>
                        <div class="fecha_mascota">
                            <p>Fecha de publicación: {{ mascota.fecha_publicacion }}</p>
                        </div>
                        <div class="desc_mascota">
                            <p>{{ mascota.descripcion|linebreaksbr }}</p>
                        </div>
                        <br>
                        <br>
                        {% endfor %}
                    </div>
                </div>
                
        </div>
    </div>
{% endblock %}

misperris/blog/templates/blog/Registro.html
{% extends 'accounts/base_accounts.html '%}

<link rel="stylesheet" href="/static/css/Style2.css">
{% block content %}

<section class="formulario">
    <br>
    <br>
    <form id="formulario-perris" method="POST" data-cities-url="{% url 'blog:load_ciudades' %}" class="post-form">
        <br>
        <h1>¡Postula para adoptar una mascota!</h1>
        <br>
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" name="submit" value="Enviar">
        <a href="{% url 'blog:home' %}"><input type="button" name="back" value="Volver"></a>

    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_region").change(function () {
            var url = $("#formulario-perris").attr("data-cities-url");  // get the url of the `load_cities` view
            var regionId = $(this).val();  // get the selected country ID from the HTML input

            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                    'region': regionId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_ciudad").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });

        });
    </script>
</section>

{% endblock %}

misperris/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<head>


    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Mis Perris</title>
    <script src="/static/Js/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="/static/fontsicon/style.css">
    <link rel="stylesheet" href="/static/css/flexboxgrid.css">
    <link rel="stylesheet" href="" type="text/css">
    <script src="static/Js/jquery.flexslider.js"></script>
    <link rel="stylesheet" href="/static/css/LightBox.css">
    <link rel="stylesheet" href="/static/css/flexslider.css">
    
    <script type="text/javascript" charset="utf-8">
        $(window).load(function () {
            $('.flexslider').flexslider();
        });
    </script>
    <script src="static/Js/script.js"></script>
    <link rel="stylesheet" href="/static/css/Style.css">

</head>

<body>
    <div class="">
        <div class="row">
            <div class="col-xs-12">
                <header>
                    <nav>
                        <ul>
                            <li>
                                <img src="/static/IMG/logo.png" alt="logo">
                            </li>
                            <li>
                                <a href="{% url 'blog:home' %}">Inicio</a>
                            </li>
                            <li>
                                <a href="#">Quiénes Somos</a>
                            </li>
                            <li>
                                <a href="#">Servicios</a>
                            </li>
                            <li>
                                <a href="#">Contáctanos</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li>
                                <a href="Registro.html">Postula AQUÍ!</a>
                            </li>
                            <li style="font-size:16px">
                                <div class="connect-message">
                                    Conectado como: {{ request.user }}
                                </div>
                            </li>
                            <li>
                                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="salir" type="submit">Salir</button>
                                </form>
                            </li>
                            {% else %}
                            <li style="font-size:20px">
                                <a href="{% url 'accounts:login' %}">INGRESA</a>
                            </li>
                            {% endif %}


                        </ul>
                    </nav>
                </header>
                <br> {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

misperris/blog/templates/blog/base_mascotas.html
<!DOCTYPE html>
<html lang="es">
{% load staticfiles %} {% load pwa %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Mis Perris</title>
    <script src="/static/Js/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="/static/fontsicon/style.css">
    <link rel="stylesheet" href="/static/css/flexboxgrid.css">
    <link rel="stylesheet" href="" type="text/css">
    <script src="static/Js/jquery.flexslider.js"></script>
    <link rel="stylesheet" href="/static/css/LightBox.css">
    <link rel="stylesheet" href="/static/css/flexslider.css">
    <script src="static/Js/script.js"></script>
    <link rel="stylesheet" href="/static/css/Style.css">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <header>
                    <nav>
                        <ul>
                            <li>
                                <img src="/static/IMG/logo.png" alt="logo">
                            </li>
                            <li>
                                <a href="{% url 'blog:home' %}">Inicio</a>
                            </li>

                            {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'blog:mascota_new' %}" class="top-menu"><span class="icon-plus agregar"></span>
                                    Agregar nueva mascota</a>
                            </li>
                            <li style="font-size:22px" class="aviso-user">
                                <div class="connect-message">
                                    Conectado como: {{ request.user }}
                                </div>
                            </li>
                            <li>
                                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="salir" type="submit">Salir</button>
                                </form>
                            </li>
                            {% else %}
                            <li style="font-size:20px">
                                <a href="{% url 'accounts:login' %}">INGRESA</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </header>
                <br> {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

misperris/blog/templates/blog/ciudad_dropdown_list_options.html
<option value="">---------</option>
{% for ciudad in ciudades %}
<option value="{{ ciudad.pk }}">{{ ciudad.nombre }}</option>
{% endfor %}

misperris/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %} 
{% load socialaccount %}

<button class="btn btn-secondary btn-block mt-5" type="submit">Ingresa</button>
<a class="btn btn-primary btn-block" href="{% provider_login_url "facebook" method="oauth2" %}">
   <span class="fab fa-facebook"></span>
      Logea con facebook
 </a>
 
{% endblock %}

misperris/blog/templates/blog/mascota_detail.html
{% extends 'blog/base_mascotas.html' %}
{% block content %}


<div class="row">
    <div class="col-xs-12">
        <div class="post-detail">
            <h1>Detalle Mascota:</h1>
            <br>
            <div class="img_detail">
                <img style="height: 400px;" src="{{ mascotas.foto.url }}">
            </div>
            {% if mascotas.fecha_publicacion %}
            <div class="date">
                Fecha de publicación: {{ mascotas.fecha_publicacion }}
            </div>
            {% endif %}
            <br>
            <h1>{{ mascotas.nombre }}</h1>
            <h2>Raza: {{ mascotas.raza }}</h2>
            <h3>Estado: {{ mascotas.estado }}</h3>
            <br>
            <p>{{ mascotas.descripcion |linebreaksbr }}</p>
            <br>
            <ul>
                <li class="modificar">
                    <a class="btn btn-default" href="{% url 'blog:mascota_edit' pk=mascotas.pk %}"><span class="icon-pencil edit"></span>
                        Modificar Mascota</a>
                </li>
                <li class="remover">
                    <a class="btn btn-default" onclick="borrarMascota()" href="{% url 'blog:mascota_delete' pk=mascotas.pk %}"><span
                            class="icon-minus delete"></span> Borrar Mascota</a>
                </li>
            </ul>
            <br>
            <input type="button" name="back" value="Volver" onclick="location.href='/Mascota_List'">
        </div>
    </div>
</div>

<script>
    function borrarMascota() {
        alert("Mascota eliminada exitosamente");
    }
</script>

{% endblock %}